### ISSUE TITLE
Open Window/Tab With Result

### ISSUE THREAD

**Issue by weilbith** [rhysd/devdocs.vim#10]
Hey!
As I found this here, I was heavily breathing. Then I realized, that it opens the search result in the web browser and not in _Vim_. Thats nice, but could be better (couldn't it?).
So what do u think about the idea to grep the resulting webpage (`wget` is enough I assume), convert this page into markdown (some nice converters are out there) and display this temporally file (`/tmp/...`) in a new window/tab (configurable). Thinking further it would be useful if the window with the last search result stays open and the user starts a new search, the window is reused.
Links in the page for further results can be opened as normal and then the browser will be opened (should be easier so far). I'm thinking about something like this [here](https://github.com/jungomi/vim-mdnquery).
Good? Bad? Awesome! Horrible...

**Comment by aemonge** [comment]
I Agree, or we could search for a browser built in vim, and tell it to open in that default browser :)

Such as https://github.com/vim-scripts/webBrowser

**Comment by weilbith** [comment]
Close since no interest from both sides anymore.
