### ISSUE TITLE
Error on opening URL in Win10

### ISSUE THREAD

**Issue by mzlogin** [rhysd/devdocs.vim#5]
![image](https://user-images.githubusercontent.com/1646590/29392397-2893d662-8330-11e7-930c-43773716c479.png)

```
处理 function devdocs#open[5]..<SNR>78_open_fallback 时发生错误：
第  18 行：
Error on opening URL: 'http://devdocs.io/#q=Long'
```

System: Win10
Vim: 8.0

A workaround for me:

change autoload/devdocs.vim#line39 from

```viml
call system('cmd /q /c start "" ' . url)
```

to

```viml
call system('cmd /q /c start "" ' . substitute(url, "'", "", "g"))
```

**Comment by rhysd** [comment]
Thank you for your report and investigation.

> call system('cmd /q /c start "" ' . substitute(url, "'", "", "g"))

I have no idea why this code change fixes this problem. From your error message, the value of variable `url` is `"http://devdocs.io/#q=Long"`, is this correct? It looks not containing single quote in the string.

**Comment by mzlogin** [comment]
I have tried `echom url`, the url string contains single quote in my environment.

**Comment by rhysd** [comment]
Could you show me the displayed value? I think I need to know how to escape.

**Comment by mzlogin** [comment]
And, I've tested in a laptop with Win7, it is the same with my Win10.

**Comment by rhysd** [comment]
I guess quoting the variable would work. I'll fix it tomorrow

**Comment by mzlogin** [comment]
Thx, problem solved, seems it's effects of `shellslash`?

**Comment by rhysd** [comment]
Yes, Vim's `shellescape` has a problem. On Windows console, it requires double quote but `shellescape` tends to use single quote when `shellslash` is on. We need to disable `shellslash` explicitly while calling `shellescape` on Windows.

**Comment by mzlogin** [comment]
Understood, thx for explain.
