### ISSUE TITLE
Open DevDocs in a browser other than the default

### ISSUE THREAD

**Issue by theunraveler** [rhysd/devdocs.vim#6]
Hello. I just started using DevDocs with vim, and have a `DevDocs` site-specific app set up with [Fluid](http://fluidapp.com). I'm wondering if it's possible to specify what browser to open links to devdocs.io in for this plugin. Thanks!

**Comment by rhysd** [comment]
I added `g:devdocs_open_cmd` in 92f6937. Please use it as described [here](https://github.com/rhysd/devdocs.vim#open-in-non-default-browser).

**Comment by theunraveler** [comment]
Thanks! I'll give it a shot first thing tomorrow.
